import { chapterMetrics, mappingStatistics, researchHighlights } from "@amdb/content";
import { pickLocalized } from "@amdb/core";
import type { AppLayout } from "../app/layout";
import { clear } from "../dom/html";
import { getLatestStatistics, type StatisticsReport } from "../services/statistics.service";

export async function renderStatistics(layout: AppLayout): Promise<void> {
  clear(layout.main);
  const language = layout.getLanguage();

  const section = document.createElement("section");
  section.className = "page-section";
  const title = document.createElement("h1");
  title.textContent = "Chapter statistics";
  const intro = document.createElement("p");
  intro.className = "lead";
  intro.textContent =
    "Review the latest generated RDF statistics alongside the published research and GSoC mapping baseline.";

  const sourceNote = document.createElement("section");
  sourceNote.className = "statistics-explainer";
  const sourceTitle = document.createElement("h2");
  sourceTitle.textContent = "How to read these numbers";
  const sourceCopy = document.createElement("p");
  sourceCopy.textContent =
    "This page combines two kinds of statistics: fixed release numbers from the Amharic DBpedia research and GSoC baseline, and live extraction numbers generated by scanning RDF output files through the backend statistics service.";
  sourceNote.append(sourceTitle, sourceCopy);

  const liveSection = document.createElement("section");
  liveSection.className = "statistics-live";
  const liveTitle = document.createElement("h2");
  liveTitle.textContent = "Latest generated extraction statistics";
  const liveStatus = document.createElement("p");
  liveStatus.className = "status";
  liveStatus.textContent = "Loading the latest statistics report from the backend...";
  const liveContent = document.createElement("div");
  liveSection.append(liveTitle, liveStatus, liveContent);

  const baselineTitle = document.createElement("h2");
  baselineTitle.textContent = "Published research baseline";
  const metrics = document.createElement("div");
  metrics.className = "metric-grid metric-grid--wide";
  for (const metric of chapterMetrics) {
    const article = document.createElement("article");
    article.className = `metric metric--${metric.tone ?? "primary"}`;
    const value = document.createElement("strong");
    value.textContent = metric.value;
    const label = document.createElement("span");
    label.textContent = pickLocalized(metric.label, language) ?? "";
    const detail = document.createElement("p");
    detail.textContent = pickLocalized(metric.detail, language) ?? "";
    article.append(value, label, detail);
    metrics.append(article);
  }

  const metricExplanations = document.createElement("div");
  metricExplanations.className = "statistics-explainer-grid";
  for (const item of [
    {
      title: "97 mapped templates",
      body: "This headline comes from the published chapter/GSoC baseline after mapping cleanup. It counts template work reported for the release. The detailed table below uses a stricter mapping-coverage denominator of 84 distinct Amharic infobox templates, which is why the two template counts are not identical.",
    },
    {
      title: "77.29% property coverage",
      body: "This is the share of template parameters that were connected to DBpedia ontology properties in the mapping baseline: 2,392 mapped properties out of 3,095 total properties.",
    },
    {
      title: "99.15% property occurrences",
      body: "This measures actual use in extracted infobox data, not only distinct property names. It means 19,799 of 19,968 property occurrences were covered after statistics were switched to the infobox-properties output.",
    },
    {
      title: "528,370 unique triples",
      body: "This is the published release size for the extracted Amharic DBpedia knowledge graph after duplicate RDF triples were removed.",
    },
  ]) {
    const article = document.createElement("article");
    article.className = "statistics-explainer-card";
    const itemTitle = document.createElement("h3");
    itemTitle.textContent = item.title;
    const itemBody = document.createElement("p");
    itemBody.textContent = item.body;
    article.append(itemTitle, itemBody);
    metricExplanations.append(article);
  }

  const table = document.createElement("table");
  table.className = "stats-table";
  const thead = document.createElement("thead");
  const headerRow = document.createElement("tr");
  for (const heading of ["Statistic", "Coverage", "Count", "Meaning"]) {
    const th = document.createElement("th");
    th.scope = "col";
    th.textContent = heading;
    headerRow.append(th);
  }
  thead.append(headerRow);
  const tbody = document.createElement("tbody");
  for (const stat of mappingStatistics) {
    const row = document.createElement("tr");
    for (const value of [stat.label, stat.percentage, stat.count, stat.description]) {
      const cell = document.createElement(value === stat.label ? "th" : "td");
      if (cell instanceof HTMLTableCellElement && value === stat.label) cell.scope = "row";
      cell.textContent = value;
      row.append(cell);
    }
    tbody.append(row);
  }
  table.append(thead, tbody);

  const highlights = document.createElement("div");
  highlights.className = "insight-grid";
  const heading = document.createElement("h2");
  heading.textContent = "Research implementation notes";
  highlights.append(heading);
  for (const item of researchHighlights) {
    const card = document.createElement("article");
    card.className = "insight-card";
    const cardTitle = document.createElement("h3");
    cardTitle.textContent = pickLocalized(item.title, language) ?? "";
    const cardBody = document.createElement("p");
    cardBody.textContent = pickLocalized(item.body, language) ?? "";
    card.append(cardTitle, cardBody);
    highlights.append(card);
  }

  section.append(
    title,
    intro,
    sourceNote,
    liveSection,
    baselineTitle,
    metrics,
    metricExplanations,
    table,
    highlights,
  );
  layout.main.append(section);

  try {
    const report = await getLatestStatistics();
    renderLiveStatistics(liveStatus, liveContent, report);
  } catch (error) {
    liveStatus.className = "status status--error";
    liveStatus.textContent =
      error instanceof Error
        ? `Live statistics unavailable: ${error.message}.`
        : "Live statistics unavailable.";
  }
}

function renderLiveStatistics(
  status: HTMLParagraphElement,
  container: HTMLDivElement,
  report: StatisticsReport,
): void {
  status.textContent = `Generated ${formatDate(report.generated_at)} using ${report.engine}.`;

  const metrics = document.createElement("div");
  metrics.className = "metric-grid metric-grid--wide";
  const values: readonly [string, number, string][] = [
    [
      "RDF triples",
      report.total_triples,
      `${report.file_count} RDF dataset files were scanned and every parsed subject-predicate-object statement was counted.`,
    ],
    [
      "Unique subjects",
      report.unique_subjects,
      "Distinct resources that appear as the subject of at least one parsed RDF triple.",
    ],
    [
      "Unique predicates",
      report.unique_predicates,
      "Distinct RDF properties used across the scanned extraction outputs.",
    ],
    [
      "Unique objects",
      report.unique_objects,
      "Distinct resource links and literal values that appear as RDF objects.",
    ],
    [
      "Mapping-based triples",
      report.mapping_based_triples,
      "Triples from files whose names indicate DBpedia mapping-based extraction output.",
    ],
    [
      "Raw infobox triples",
      report.raw_infobox_triples,
      "Triples from raw infobox output files, before every field is normalized through DBpedia mappings.",
    ],
  ];
  for (const [label, value, detail] of values) {
    const article = document.createElement("article");
    article.className = "metric";
    const strong = document.createElement("strong");
    strong.textContent = formatNumber(value);
    const span = document.createElement("span");
    span.textContent = label;
    const paragraph = document.createElement("p");
    paragraph.textContent = detail;
    article.append(strong, span, paragraph);
    metrics.append(article);
  }

  const native = document.createElement("p");
  native.className = "statistics-live__native";
  native.textContent = report.native_def_stats.attempted
    ? `DEF-native statistics: ${report.native_def_stats.success ? "completed successfully" : "failed"}.`
    : "DEF-native statistics were not requested for this report.";

  const datasetTitle = document.createElement("h3");
  datasetTitle.textContent = "Largest extracted datasets";
  const table = document.createElement("table");
  table.className = "stats-table";
  const header = document.createElement("tr");
  for (const label of ["Dataset", "Triples", "Subjects", "Predicates", "Skipped lines"]) {
    const cell = document.createElement("th");
    cell.scope = "col";
    cell.textContent = label;
    header.append(cell);
  }
  const thead = document.createElement("thead");
  thead.append(header);
  const tbody = document.createElement("tbody");
  const datasets = [...report.dataset_statistics]
    .sort((left, right) => right.triple_count - left.triple_count)
    .slice(0, 10);
  for (const dataset of datasets) {
    const row = document.createElement("tr");
    const name = document.createElement("th");
    name.scope = "row";
    name.textContent = dataset.dataset_name;
    row.append(name);
    for (const value of [
      dataset.triple_count,
      dataset.subject_count,
      dataset.predicate_count,
      dataset.skipped_lines,
    ]) {
      const cell = document.createElement("td");
      cell.textContent = formatNumber(value);
      row.append(cell);
    }
    tbody.append(row);
  }
  table.append(thead, tbody);

  container.append(metrics, native, datasetTitle, table);
}

function formatNumber(value: number): string {
  return new Intl.NumberFormat("en-US").format(value);
}

function formatDate(value: string): string {
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}
